export const TAGS = [
  "Frontend",
  "Backend",
  "Fullstack",
  "DevOps",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Cloud Computing",
  "Cybersecurity",
  "Blockchain",
  "Mobile Development",
  "UI/UX Design",
  "Game Development",
  "Python",
  "JavaScript",
  "TypeScript",
  "React",
  "Angular",
  "Vue",
  "Node.js",
  "Java",
  "C#",
  "SQL",
  "NoSQL",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "GCP",
  "Linux",
  "Networking",
  "Agile",
  "Scrum",
  "Git",
  "Microservices",
  "Testing",
  "Automation",
  "Big Data",
  "Data Analytics",
  "Computer Vision",
];

export const CATEGORIES = [
  "Web Development",
  "Mobile Development",
  "Game Development",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Cloud Computing",
  "Cybersecurity",
  "Blockchain",
  "UI/UX Design",
  "DevOps",
  "Software Engineering",
  "Database Management",
  "Networking",
  "Embedded Systems",
  "IT Project Management",
  "Testing & QA",
  "Big Data",
  "Computer Vision",
  "Automation",
];
